version: "3"

services:
  
  puppeteer:
    image: sendmail:latest
    build: .
    volumes:
      # mount code and output directories into the container
      - ./output:/app/output
      - /home/harshit/docker-puppeteer-dev/code:/app/code
    working_dir: /app/code
    shm_size: 1gb #512M
    # just run the container doing nothing
    entrypoint: ["sh", "-c", "sleep infinity"]
